server:
   port: 9999
   
spring:
    h2:
     console:
      enabled: true
    datasource:
     url: jdbc:h2:mem:testdb
    application:
     name: PAYMENT-SERVICE
     

logging:
  file:
    path: E:\var\mission_antyodaya_data\microservice\log